# Marker Repo - calculations

## Loading packages

In [1]:
import marker_repo as mr
import calculations as calc

## Settings

In [2]:
# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists"
# The name of the new list which will be exported
export_name = "weighted_human_marker_list"

## Calculate scores

In [3]:
# Show selected lists
keywords = {"organism_organism_name": "human"}
mr.search_db(mr.get_db(REPO_LISTS_PATH), keywords, case_sensitive=False, exact=False)

,list_name,organism_organism_name,organism_taxonomy_id,marker_type,submitter_name,submitter_email,date,source,tags_tissue,tags_custom_tag
id,,,,,,,,,,
1,panglao_human_adrenal-glands,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,adrenal-glands,cell type annotation
2,panglao_human_blood,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,blood,cell type annotation
3,panglao_human_bone,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,bone,cell type annotation
4,panglao_human_brain,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,brain,cell type annotation
5,panglao_human_connective-tissue,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,connective-tissue,cell type annotation
...,...,...,...,...,...,...,...,...,...,...
79,hcm_human_gingiva,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,gingiva,cell type annotation
80,hcm_human_gonad,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,gonad,cell type annotation
81,hcm_human_gut,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,gut,cell type annotation
82,hcm_human_head,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,head,cell type annotation
83,hcm_human_head-and-neck,human,9606,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,head-and-neck,cell type annotation

In [4]:
# Compare all lists containing the corresponding keywords
df = calc.compare_marker_lists(REPO_LISTS_PATH, keywords)

In [5]:
# Transform score to ubiquitousness index
df = calc.invert_score(df)
display(df)

                                   Info                  Marker  Score
22147          Ciliated epithelial cell  CCDC65 ENSG00000139537    0.0
4046                Gamma delta T cells   TRDJ4 ENSG00000211826    0.0
28755                      Sertoli cell  KLHL15 ENSG00000174010    0.0
17056            Lake et al.Science.Ex1   GPR83 ENSG00000123901    0.0
7861          Endothelial cells (aorta)    KLK8 ENSG00000129455    0.0
...                                 ...                     ...    ...
14310           Hematopoietic stem cell   PTPRC ENSG00000081237    1.0
15841  Central nervous system stem cell   PTPRC ENSG00000081237    1.0
3918                    Dendritic cells   PTPRC ENSG00000081237    1.0
8072              Mesenchymal stem cell   PTPRC ENSG00000081237    1.0
14550                        Lymphocyte   PTPRC ENSG00000081237    1.0

[29410 rows x 3 columns]

In [6]:
# Export list with scores
mr.export_marker_list(REPO_LISTS_PATH, export_name, df)

Combined list saved: /mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists/weighted_human_marker_list