# Marker Repo - Search within lists

## Loading packages

In [1]:
import marker_repo as mr

## Settings

In [2]:
# The path of the list to be searched
LIST_PATH = "/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood"

# The path were the corresponding metadata file is located
# None, if you like to add the metadata manually
METADATA_PATH = None

## Search list

### Load list

In [3]:
df = mr.getList(LIST_PATH, "celltype")
df

         Cell type   Marker
0    Erythroblasts      CGA
1    Erythroblasts     GPHa
2    Erythroblasts    GPHA1
3    Erythroblasts     FSHA
4    Erythroblasts      LHA
..             ...      ...
880  Reticulocytes    CD49d
881  Reticulocytes    CD49D
882  Reticulocytes  SLC11A2
883  Reticulocytes     DCT1
884  Reticulocytes   NRAMP2

[885 rows x 2 columns]

### Enter keywords

In [4]:
keywords = {"Cell type": "Ret"}

## Search list

In [5]:
filtered_df = mr.searchDB(df, keywords, exact=False)
filtered_df

        Cell type    Marker
0   Reticulocytes    RUVBL1
1   Reticulocytes     TIP49
2   Reticulocytes    NMP238
3   Reticulocytes      RVB1
4   Reticulocytes    TIP49a
5   Reticulocytes  Pontin52
6   Reticulocytes     ECP54
7   Reticulocytes      Rvb1
8   Reticulocytes    INO80H
9   Reticulocytes      TFRC
10  Reticulocytes      CD71
11  Reticulocytes      TFR1
12  Reticulocytes       p90
13  Reticulocytes      UCP3
14  Reticulocytes   SLC25A9
15  Reticulocytes     FOLR1
16  Reticulocytes      FOLR
17  Reticulocytes     UBE2O
18  Reticulocytes   E2-230K
19  Reticulocytes      CD36
20  Reticulocytes    SCARB3
21  Reticulocytes      GPIV
22  Reticulocytes       GP4
23  Reticulocytes      GP3B
24  Reticulocytes     ITGA4
25  Reticulocytes     CD49d
26  Reticulocytes     CD49D
27  Reticulocytes   SLC11A2
28  Reticulocytes      DCT1
29  Reticulocytes    NRAMP2