# Marker Repo - scoring

In this notebook, individual markers can be weighted using various functions. In addition, BioMart or the HomoloGene DB enable genes to be transferred from a source organism to a target organism. Thus, even analyses with specific organisms can be performed without already existing suitable lists.

## Loading packages

In [1]:
import markerrepo.marker_repo as mr
import markerrepo.scoring as score
import markerrepo.utils as utils
import markerrepo.wrappers as wrap
import markerrepo.plotting as plot

%load_ext autoreload
%autoreload 2

/mnt/workspace2/jdetlef/.conda/envs/marker-repo/lib/python3.14/site-packages/markerrepo/wrappers.py:23: RuntimeWarning: Please install the latest sctoolbox version. Some functionality may not be available.
  warnings.warn("Please install the latest sctoolbox version. Some functionality may not be available.", RuntimeWarning)

## Settings

Specify path of the cloned repository.

In [2]:
repo_path = "/mnt/workspace2/jdetlef/repos/annotate_by_marker_and_features"

# Calculate scores

This part compares and scores markers from selected marker lists using <b>ubiquitousness index</b>.
A score of '0' signifies that the marker is the most specific within this selection, 
while a score of '1' indicates that the marker is the most prevalent.

Start by selecting lists you want to compare.

In [3]:
results = mr.guided_search(repo_path=repo_path, out="marker_list")

Available columns for search:
1: ID
2: List name
3: Organism name
4: Taxonomy ID
5: Marker type
6: Submitter name
7: Source
8: List type
9: tags_transferred
10: Email
n: Next page
Enter identifier of column to search in (leave blank to search in all columns):
Enter search terms (separated by commas, '-' for negative search):
Number of results: 306
Do you want to see the results? (yes/no): yes

,index,List name,Organism name,Taxonomy ID,Marker type,Submitter name,Source,List type,tags_transferred,Email,Tissue,Genome version,Date,Life stage,tags_age,tags_info,Marker,Info
ID,,,,,,,,,,,,,,,,,,
1688745545837,0,HCM_human_fetus,human,9606,Genes,"Kessler, Micha Frederick",bio-bigdata.hrbmu.edu.cn/CellMarker,Cell type annotation,NaN,Micha-Frederick.Kessler@mpi-bn.mpg.de,fetus,NaN,27.03.2020,NaN,NaN,NaN,"[EMCN, ENSG00000164035, CD8A, ENSG00000153563,...","[T cell, Pan-endothelial cell, Stromal cell, M..."
17083323392210,1,human_gender_genes,human,9606,Genes,"Kessler, Micha Frederick",sctoolbox,Gender,NaN,Micha-Frederick.Kessler@mpi-bn.mpg.de,NaN,NaN,NaN,NaN,NaN,NaN,"[EIF3MP1, ENSG00000236365, SSX1, ENSG000001267...",[Gender genes]
17103172789694,2,stomach_SM-CHLWL,human,9606,Genomic regions,"Kessler, Micha Frederick",catlas.org,Cell type annotation,NaN,Micha-Frederick.Kessler@mpi-bn.mpg.de,stomach,hg38,NaN,NaN,NaN,NaN,"[CHR5:67215815-67216215, CHR21:41593222-415936...","[stomach neuroendocrine cell, CD8-positive, al..."
168874554211252,3,Panglao_human_skin,human,9606,Genes,"Kessler, Micha Frederick",panglao.se,Cell type annotation,NaN,Micha-Frederick.Kessler@mpi-bn.mpg.de,skin,NaN,27.03.2020,NaN,NaN,NaN,"[HLA-DRB1, ENSG00000196126, KRT1, ENSG00000167...","[Sebocytes, Melanocytes, Merkel cells, Trichoc..."
168874554264756,4,Panglao_human_lungs,human,9606,Genes,"Kessler, Micha Frederick",panglao.se,Cell type annotation,NaN,Micha-Frederick.Kessler@mpi-bn.mpg.de,lung,NaN,27.03.2020,NaN,NaN,NaN,"[SPDEF, ENSG00000124664, CFTR, ENSG00000001626...","[Ionocytes, Alveolar macrophages, Pulmonary al..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1741686472783908,301,zebrafish_cranial_neural_crest_spatial_domain_...,zebrafish,7955,Genes,"Schultheis, Hendrik",https://doi.org/10.1038/s41467-021-27594-w,Cell type annotation,NaN,hendrik.schultheis@mpi-bn.mpg.de,cranial neural crest,NaN,NaN,embryo,1.5 dpf,NaN,"[PITX2, ENSDARG00000036194, EMX2, ENSDARG00000...","[Frontonasal, Cycling, Dorsal, Ventral, Interm..."
1741686677329305,302,zebrafish_cranial_neural_crest_14dpf,zebrafish,7955,Genes,"Schultheis, Hendrik",https://doi.org/10.1038/s41467-021-27594-w,Cell type annotation,NaN,hendrik.schultheis@mpi-bn.mpg.de,cranial neural crest,NaN,NaN,child,14 dpf,NaN,"[MYH11A, ENSDARG00000009782, CXCL12A, ENSDARG0...","[Tendon/ligament, Perivascular, Hyaline cartil..."
1741687334852231,303,zebrafish_non_cranial_neural_crest,zebrafish,7955,Genes,"Schultheis, Hendrik",https://doi.org/10.1038/s41467-021-27594-w,Cell type annotation,NaN,hendrik.schultheis@mpi-bn.mpg.de,cranial neural crest,NaN,NaN,NaN,NaN,non cranial neural crest,"[HBBE2, ENSDARG00000045143, EPCAM, ENSDARG0000...","[Epithelia, Blood]"
1741687684295404,304,zebrafish_non_mesenchymal_cranial_neural_crest,zebrafish,7955,Genes,"Schultheis, Hendrik",https://doi.org/10.1038/s41467-021-27594-w,Cell type annotation,NaN,hendrik.schultheis@mpi-bn.mpg.de,cranial neural crest,NaN,NaN,NaN,NaN,non-mesenchymal cranial neural crest derivatives,"[MITFA, ENSDARG00000003732, AOX5, ENSDARG00000...","[Iridophores, Melanocytes, Otic cells, Xanthop..."
1754382986749505,305,heart_tarasco,zebrafish,7955,Genes,"Alayoubi, Yousef",Marco Tarasco,Cell type annotation,NaN,yousef.alayoubi@mpi-bn.mpg.de,heart,NaN,NaN,NaN,NaN,NaN,"[SAMSN1A, ENSDARG00000054543, ESAMA, ENSDARG00...","[Blood - red blood cells, Blood - Immune cells..."

Do you want to continue searching? (yes/no): no

Compare the lists and show the new DataFrame.

In [4]:
results_scored = score.compare_marker_lists(marker_df=results)
display(results_scored)

                           Marker                       Info  Score
143642         U7 ENSG00000276376               Gender genes    0.0
143643   RPS17P17 ENSG00000225758               Gender genes    0.0
143645  LINC00632 ENSG00000203930               Gender genes    0.0
143647   MIR320D2 ENSG00000221081               Gender genes    0.0
143648    SPANXB1 ENSG00000227234               Gender genes    0.0
...                           ...                        ...    ...
176698        CD4 ENSG00000010610  Proliferative CD4+ T cell    1.0
173767        CD4 ENSG00000010610            Effector T cell    1.0
173781        CD4 ENSG00000010610                 Lymphocyte    1.0
175936        CD4 ENSG00000010610   Memory regulatory T cell    1.0
190958        CD4 ENSG00000010610           Naive CD4 T cell    1.0

[147379 rows x 3 columns]

With this function all marker scores, which are part of the <b>panglaoDB</b>, are being updated by using the calculated ubiquitousness index from the panglaoDB. The resulting DataFrame thus contains the dynamically calculated scores as well as scores of the panglaoDB - depending on whether the corresponding gene is present in the panglaoDB or not.

In [5]:
results_panglao = score.update_scores(repo_path=repo_path, df=results_scored)
display(results_panglao)

                          Marker                        Info  Score
60278     CHR6:11650320-11650720            endothelial cell  0.000
27739     CHR9:95091906-95092306     respiratory goblet cell  0.000
27751    CHR12:82314350-82314750     respiratory goblet cell  0.000
27753     CHR9:95092334-95092734     respiratory goblet cell  0.000
27755   CHR6:125597571-125597971     respiratory goblet cell  0.000
...                          ...                         ...    ...
174122     ITM2B ENSG00000136156  CD1C-CD141- dendritic cell  0.854
135852  ITM2B ENSMUSG00000022108                Müller cells  0.854
4936    ITM2B ENSRNOG00000016271                Müller cells  0.854
192407     ITM2B ENSG00000136156             Microglial cell  0.854
180885     ITM2B ENSG00000136156                   Astrocyte  0.854

[147379 rows x 3 columns]

Finally the scored list can be exported.

In [6]:
mr.export_marker_list(results_panglao, file_name="Scored", marker_id="symbol")

Folder /mnt/workspace2/jdetlef/repos/annotate_by_marker_and_features/notebooks/exported_lists created.
Marker list saved: /mnt/workspace2/jdetlef/repos/annotate_by_marker_and_features/notebooks/exported_lists/Scored

'/mnt/workspace2/jdetlef/repos/annotate_by_marker_and_features/notebooks/exported_lists/Scored.csv'